---
title: "A Guide to Statistics"
subtitle: "A Concise Introduction with Examples in R"
author: |
  | **Trang Bui**
date: "`r Sys.Date()`"
site: bookdown::bookdown_site
biblio-style: apalike
link-citations: true
bibliography: references.bib
output: 
  bookdown::gitbook:
    css: style.css
    fig_caption: yes
    includes:
      in_header: preamble.html
---

```{r setup, include=FALSE}
# common functions
# contributors should be aware of these and use them whenever possible.
source("common_functions.R")

# common figpath
fig.path <- "data/images/"
```

# Preface {-}

Statistics is the study of data, from collecting, analyzing, to making conclusions about the data. It is crucial that you know statistics if you work with any research that uses data. This book presents a short and gentle introduction to statistics. You will learn some basic (i) concepts about data and their summaries, (ii) statistical tools to analyze them, and (iii) how to implement them in **R**. 

The book will be helpful for those of you who just getting started, as well as those want to have a better and more systematic understanding. In writing the book, as well as when I was writing the lecture notes, I try to present the ideas as clear as possible, including examples and thought exercises throughout the chapters. Although the book will help build and strengthen your knowledge from square one, and will present simple solutions to several basic yet fundamental problems, I hope it will still inspire you to go further and explore more about this broad field of statistics. 

The content of the book follows closely my lecture notes for [AFM 113](https://uwflow.com/course/afm113) at University of Waterloo. I would like to thank Ms. [Dina Dawoud](https://uwaterloo.ca/statistics-and-actuarial-science/people-profiles/dina-dawoud) for helping me build structure of the lecture notes, and hence this book.

